name: CardsiOS

options:
  bundleIdPrefix: com.jakkuazzo
  deploymentTarget:
    iOS: "17.0"

targets:
  CardsiOS:
    type: application
    platform: iOS
    sources:
      - path: CardsiOS
      - path: Resources/packs.json
        buildPhase: resources
      - path: "Resources/AR Resources.arresourcegroup"
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jakkuazzo.cardsios
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: CardsiOS/Info.plist
        SWIFT_VERSION: 5.0
  CardsiOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CardsiOSTests
    dependencies:
      - target: CardsiOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jakkuazzo.cardsios.tests
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.0
